server:
  port: 8761

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8888/"                  #change localhost to configserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"