server:
  port: 8081


spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://configserver:8888/"    # this property is not required for docker-compose. But required if we want to run mvn clean install.
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: false
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    connection-timeout: 10s

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    #change eurekaserver to localhost, if running application from IntelliJ
info:
  app:
    name: "cards"
    description: "Cards Application"
    version: "1.0.0"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    com:
      sumit:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"