services:
  accounts:
    build:
      context: .
      dockerfile: ./accounts/Dockerfile
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sumit-network
  cards:
    build:
      context: .
      dockerfile: ./cards/Dockerfile
    container_name: cards-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sumit-network
  loans:
    build:
      context: .
      dockerfile: ./loans/Dockerfile
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sumit-network

networks:
  sumit-network:
    driver: "bridge"