server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://configserver:8888/"    # this property is not required for docker-compose. But required if we want to run mvn clean install.
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
  data:
    redis:
      connect-timeout: 3s
      host: redis             #change redis to localhost, if running application from IntelliJ
      port: 6379
      timeout: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"    # to download public certificate from keycloak


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Edge Server/API Gateway"
    version: "1.0.0"

logging:
  level:
    com:
      sumit:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"