server:
  port: 8082

spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8888/"    # this property is not required for docker-compose. But required if we want to run mvn clean install.
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    show-sql: false
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
info:
  app:
    name: "loans"
    description: "Loans Application"
    version: "1.0.0"