server:
  port: 8761

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://configserver:8888/"    # this property is not required for docker-compose. But required if we want to run mvn clean install.

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
