apiVersion: v1
kind: Secret
metadata:
  name: sumitbank-secret
type: Opaque
stringData:
  # RabbitMQ
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"

  # Databases
  MYSQL_ACCOUNTS_DATABASE_USERNAME: "root"
  MYSQL_ACCOUNTS_DATABASE_PASSWORD: "root"

  MYSQL_CARDS_DATABASE_USERNAME: "root"
  MYSQL_CARDS_DATABASE_PASSWORD: "root"

  MYSQL_LOANS_DATABASE_USERNAME: "root"
  MYSQL_LOANS_DATABASE_PASSWORD: "root"

  # Keycloak (internal k8s service)
  KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: "admin"