apiVersion: apps/v1
kind: Deployment                               # Defines a Deployment (to manage the ReplicaSets)
metadata:
  name: cards-deployment                       # Name of the Deployment
  labels:
    app: cards                                 # Deployment label (for identification)
spec:
  replicas: 1                                  # Desired number of Pods
  selector:
    matchLabels:
      app: cards                               # Deployment selector, used by deployment to find the pods where app=cards. Deployment says: I will manage ONLY Pods whose label is app=cards
  template:
    metadata:
      labels:
        app: cards                             # Pod label (used by Deployment (via ReplicaSet) to find Pods)
    spec:
      containers:
        - name: cards                          # Container name inside the Pod
          image: sumitmittal2022/cards:1.0     # Docker image of card MS
          ports:
            - containerPort: 8081              # container will start internally on this port (should be same as target port of service)
          env:

            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sumitbank-configmap
                  key: CARDS_APPLICATION_NAME

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: sumitbank-configmap
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: sumitbank-configmap
                  key: SPRING_CONFIG_IMPORT

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sumitbank-configmap
                  key: MYSQL_CARDS_DATABASE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sumitbank-secret
                  key: MYSQL_CARDS_DATABASE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sumitbank-secret
                  key: MYSQL_CARDS_DATABASE_PASSWORD

            # RabbitMQ (Spring Cloud Bus)
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: sumitbank-configmap
                  key: RABBITMQ_HOST

            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                 configMapKeyRef:
                   name: sumitbank-configmap
                   key: RABBITMQ_PORT

            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sumitbank-secret
                  key: RABBITMQ_USERNAME

            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sumitbank-secret
                  key: RABBITMQ_PASSWORD

---
apiVersion: v1
kind: Service                                  # Defines a Service (to provide network access to our Pods)
metadata:
  name: cards                                  # Service name (DNS: cards)
spec:
  selector:
    app: cards                                 # service label (Selects Pods with this label)
  type: LoadBalancer                           # Exposes service outside the cluster
  ports:
    - protocol: TCP
      port: 8081                               # k8s pod will be exposed to outside world on this port
      targetPort: 8081                         # k8s pod/container will start on this port