services:

  # RabbitMQ for Refresh configs using spring cloud bus ##################################################################
  # RabbitMQ for Event driven microservices ##############################################################################

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: base-config


  # Kafka for Event driven microservices #################################################################################

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Pk
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-config


  # Redis for Gateway Rate Limiter #######################################################################################

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config


  # Keycloak as Auth Server ##############################################################################################

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    ports:
      - "127.0.0.1:7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-config





  # All Database instances ###############################################################################################

  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: database-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: database-config

  loansdb:
    container_name: loansdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: database-config


  # Config server for managing configurations outside business logic #####################################################

  configserver:
    build:
      context: ../../configserver   # root folder where configserver folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/configserver:1.0"
    container_name: configserver-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent configserver:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config
    environment:
      OTEL_SERVICE_NAME: "configserver"


  # Eureka server for Service Discovery ##################################################################################

  eurekaserver:
    build:
      context: ../../eurekaserver   # root folder where eurekaserver folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/eurekaserver:1.0"
    container_name: eurekaserver-ms
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent eurekaserver:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 20s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      OTEL_SERVICE_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: eurekaserver-config


  # All microservices ####################################################################################################

  accounts:
    build:
      context: ../../accounts   # root folder where accounts folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/accounts:1.0"
    container_name: accounts-ms
    #ports:
    #  - "8080:8080"         # as we do not want to expose our MS outside cluster directly, it should be accessed by gateway server of same cluster
    depends_on:
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent accounts:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      OTEL_SERVICE_NAME: "accounts"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common-config.yml
      service: microservice-config

  cards:
    build:
      context: ../../cards   # root folder where cards folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/cards:1.0"
    container_name: cards-ms
    #ports:
    #  - "8081:8081"         # as we do not want to expose our MS outside cluster directly, it should be accessed by gateway server of same cluster
    depends_on:
      eurekaserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent cards:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
      OTEL_SERVICE_NAME: "cards"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-config

  loans:
    build:
      context: ../../loans   # root folder where loans folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/loans:1.0"
    container_name: loans-ms
    #ports:
    #  - "8082:8082"         # as we do not want to expose our MS outside cluster directly, it should be accessed by gateway server of same cluster
    depends_on:
      eurekaserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent loans:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      OTEL_SERVICE_NAME: "loans"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-config


  # Message microservice for Event Driven MicroServices ##################################################################

  message:
    build:
      context: ../../message   # root folder where cards folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/message:1.0"
    container_name: message-ms
    depends_on:
      #rabbit:
      #  condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      #SPRING_RABBITMQ_HOST: "rabbit"
      OTEL_SERVICE_NAME: "message"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common-config.yml
      service: microservice-config


  # Gateway server for single point entry & cross-cutting concerns #######################################################

  gatewayserver:
    build:
      context: ../../gatewayserver   # root folder where gatewayserver folder exist
      dockerfile: Dockerfile
    #image: "sumitbank/gatewayserver:1.0"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      redis:
        condition: service_healthy
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-config





  # Loki (Logs Aggregator) Read component ################################################################################

  read:
    image: grafana/loki:3.6.2
    container_name: loki-read
    command: "-config.file=/etc/loki/config.yml -target=read"
    ports:
      - "3101:3100"
    volumes:
      - ../observability/loki/loki-config.yml:/etc/loki/config.yml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      sumit-network:
        aliases:
          - loki


  # Loki (Logs Aggregator) Write component ###############################################################################

  write:
    image: grafana/loki:3.6.2
    container_name: loki-write
    command: "-config.file=/etc/loki/config.yml -target=write"
    ports:
      - "3102:3100"
    volumes:
      - ../observability/loki/loki-config.yml:/etc/loki/config.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns


  # Alloy/Promtail : Log Agent which will pull logs from All MS in same network ##########################################

  alloy:
    image: grafana/alloy:v1.12.0
    container_name: alloy
    volumes:
      - ../observability/alloy/alloy-local-config.yml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    depends_on:
      - gateway
    extends:
      file: common-config.yml
      service: network-config


  # To store all the logs from Loki Write and provide it to Loki Read when requested #####################################

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    extends:
      file: common-config.yml
      service: network-config


  # Prometheus as Events aggregator ######################################################################################

  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extends:
      file: common-config.yml
      service: network-config


  # Tempo for distributed tracing ########################################################################################

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ../observability/tempo/tempo.yml:/etc/tempo-config.yml
    extends:
      file: common-config.yml
      service: network-config


  # Grafana for Logs UI ##################################################################################################
  # Gateway : main man between A, L, G       Alloy ---(Gateway)---> Loki ---(Gateway)---> Grafana ########################

  grafana:
    image: grafana/grafana:12.3.0
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    ports:
      - "3000:3000"
    volumes:
      - ../observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-config

  backend:
    image: grafana/loki:3.6.2
    container_name: grafana-backend
    volumes:
      - ../observability/loki/loki-config.yml:/etc/loki/config.yml
    ports:
      - "3100"
      - "7946:7946"
    command: "-config.file=/etc/loki/config.yml -target=backend -legacy-read-mode=false"
    depends_on:
      - gateway
    extends:
      file: common-config.yml
      service: network-config

  gateway:
    image: nginx:1.29.3
    container_name: grafana-gateway
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1
  
        events {
          worker_connections   1000;
        }
  
        http {
          resolver 127.0.0.11;
  
          server {
            listen             3100;
  
            location = / {
              return 200 'OK';
              auth_basic off;
            }
  
            location = /api/prom/push {
              proxy_pass       http://write:3100\$$request_uri;
            }
  
            location = /api/prom/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }
  
            location ~ /api/prom/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
  
            location = /loki/api/v1/push {
              proxy_pass       http://write:3100\$$request_uri;
            }
  
            location = /loki/api/v1/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }
  
            location ~ /loki/api/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-config



networks:
  sumit-network:
    driver: bridge

volumes:
  rabbitmq-data: