services:
  network-config:
    networks:
      - sumit-network

  database-config:
    extends:
      service: network-config
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root



  base-config:
    extends:
      service: network-config
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  configserver-config:
    extends:
      service: base-config

  eurekaserver-config:
    extends:
      service: configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888/

  microservice-config:
    extends:
      service: eurekaserver-config
    environment:
      SPRING_PROFILES_ACTIVE: prod