services:

# All Database instances

  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: database-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: database-config

  loansdb:
    container_name: loansdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: database-config


# RabbitMQ for Refresh configs using spring cloud bus

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: base-config


# Redis for Gateway Rate Limiter

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config


# Config server for managing configurations outside business logic

  configserver:
    build:
      context: ../../configserver   # root folder where configserver folder exist
      dockerfile: Dockerfile
    container_name: configserver-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent configserver:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: configserver-config


# Eureka server for Service Discovery

  eurekaserver:
    build:
      context: ../../eurekaserver   # root folder where eurekaserver folder exist
      dockerfile: Dockerfile
    container_name: eurekaserver-ms
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent eurekaserver:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: eurekaserver-config


# All microservices

  accounts:
    build:
      context: ../../accounts   # root folder where accounts folder exist
      dockerfile: Dockerfile
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent accounts:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-config

  cards:
    build:
      context: ../../cards   # root folder where cards folder exist
      dockerfile: Dockerfile
    container_name: cards-ms
    ports:
      - "8081:8081"
    depends_on:
      eurekaserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent cards:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-config

  loans:
    build:
      context: ../../loans   # root folder where loans folder exist
      dockerfile: Dockerfile
    container_name: loans-ms
    ports:
      - "8082:8082"
    depends_on:
      eurekaserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent loans:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-config


# Gateway server for single point entry & cross-cutting concerns

  gatewayserver:
    build:
      context: ../../gatewayserver   # root folder where gatewayserver folder exist
      dockerfile: Dockerfile
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      redis:
        condition: service_healthy
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-config


networks:
  sumit-network:
    driver: bridge